# Build CHKPESEL.EXE

CHKPESEL.EXE: MAIN.OBJ CD.OBJ CI.OBJ GBD.OBJ GCL.OBJ GP.OBJ GA.OBJ
              TLINK /x MAIN.OBJ+CD.OBJ+CI.OBJ+GBD.OBJ+GCL.OBJ+GP.OBJ+GA.OBJ,CHKPESEL.EXE,,ALGS.LIB

MAIN.OBJ: CLEAN MAIN.ASM
          TASM /m3 MAIN.ASM
CLEAN:
       DEL MAIN.OBJ

CD.OBJ: CD.ASM
        TASM /m3 CD.ASM
CI.OBJ: CI.ASM
        TASM /m3 CI.ASM
GBD.OBJ: GBD.ASM
         TASM /m3 GBD.ASM
GCL.OBJ: GCL.ASM
         TASM /m3 GCL.ASM
GP.OBJ: GP.ASM
        TASM /m3 GP.ASM
GA.OBJ: GA.ASM
        TASM /m3 GA.ASM

# ALGS.LIB - Algorytmy wyznaczania: roku przestepnego
#                                   sumy kontrolnej
#                                   dnia tygodnia
#
# Optymalne, nie beda juz zmienianie.

ALGS.LIB: LY.OBJ CS.OBJ DOW.OBJ
          tlib ALGS.LIB +LY.OBJ +CS.OBJ +DOW.OBJ

LY.OBJ: LY.ASM
        TASM /m3 LY.ASM
CS.OBJ: CS.ASM
        TASM /m3 CS.ASM
DOW.OBJ: DOW.ASM
         TASM DOW.ASM